# Generated by Django 3.0.8 on 2020-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChessBoard',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.DeleteModel(
            name='Exam_type',
        ),
    ]
