# Generated by Django 3.0.8 on 2020-09-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('exam', '0004_exam_result2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_result2',
            name='subject',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='subjectarry', to='student.CourseSubject'),
        ),
    ]
