# Generated by Django 3.0.8 on 2020-09-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200917_0447'),
        ('exam', '0005_auto_20200915_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_result',
            name='subject',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='student.CourseSubject'),
        ),
    ]
