# Generated by Django 3.0.8 on 2020-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200915_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'Student')], default=1, max_length=254),
        ),
    ]
