# Generated by Django 3.0.8 on 2020-09-15 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('Class', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='documents/student-photo/')),
                ('admission_date', models.DateField()),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=4)),
                ('blood_group', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=254)),
                ('national_id', models.CharField(max_length=254)),
                ('previous_school_information', models.CharField(max_length=254)),
                ('previous_school_name', models.CharField(max_length=254)),
                ('previous_class', models.CharField(max_length=254)),
                ('previous_certificate', models.FileField(blank=True, null=True, upload_to='documents/certificate/')),
                ('mother_name', models.CharField(max_length=254)),
                ('father_name', models.CharField(max_length=254)),
                ('health_condition_certificate', models.FileField(blank=True, null=True, upload_to='documents/health')),
                ('academic_year', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='student.AcademicYear')),
                ('course', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='student.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('Class', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Class')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Courses')),
            ],
        ),
    ]
